apiVersion: v1

kind: Service

metadata:
  name: flask-service
  labels:
    app: flask-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  selector:
    app: flask-pod
